# Generated by Django 4.1.2 on 2022-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/blogs_img/'),
        ),
    ]
