# Generated by Django 4.1.2 on 2022-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
