# Generated by Django 4.1.2 on 2022-10-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
